version: '3'

services:
  frontend:
    image: node-frontend
    container_name: node-frontend
    ports:
      - "3000:3000"
    depends_on: 
      - java-backend

  # Backend Java Application
  backend:
    image: java-backend
    container_name: java-backend
    ports:
      - "8080:8080"
    depends_on:
      - java-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=devpass

  # MySQL Database
  database:
    image: mysql:latest
    container_name: java-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: java-spring
      MYQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: devpass
    volumes:
      - ./data:/var/lib/mysql  
  
  # Redis
  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
    networks:
      - java-backend

# Nginx
  proxy:
      image: nginx:1.21
      ports:
        - "3000:80"
      depends_on:
        - backend
        - frontend
      volumes:
        - "./proxy/default.conf:/etc/nginx/conf.d/default.conf:default.conf"